version: 2.1

workflows:
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - yarn_install
      - run: yarn build
      - run: yarn test

commands:
  yarn_install:
    steps:
      - restore_cache:
          name: Restore Yarn cache
          keys:
            - yarnpkg-v1-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn cache
          key: yarnpkg-v1-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules