version: '3'

volumes:
  postgres:
    driver: local

services:
  db:
    image: postgres:10.4
    environment:
      - POSTGRES_USER=tyql
      - POSTGRES_PASSWORD=tyql
      - POSTGRES_DB=sample
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./sqls:/docker-entrypoint-initdb.d
    ports:
      - '5433:5432'
